extends: default

rules:
  comments:
    min-spaces-from-content: 1 # To be compatible with Prettier
  document-start:
    present: false # Don't need document start markers
  line-length: disable # Delegate to Prettier
  truthy:
    allowed-values: ["true", "false", "on"] # https://github.com/adrienverge/yamllint/issues/158#issuecomment-536735525
  quoted-strings:
    required: only-when-needed
