name: spell-check-pr

on:
  pull_request:
  workflow_call:
    inputs:
      cspell-json-url:
        required: false
        type: string
        default: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set cspell-json-url
        run: |
          CSPELL_JSON_URL=${{ inputs.cspell-json-url }}
          echo "CSPELL_JSON_URL=${CSPELL_JSON_URL:=https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json}" >> $GITHUB_ENV

      - name: Retrieve spell check dictionary
        run: |
          curl -fsSL -o .cspell.json \
            ${{ env.CSPELL_JSON_URL }}

      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v1.3.5
        with:
          config: .cspell.json
